version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=taskapp
      - DB_PORT=3306
    command: npm run dev

  db:
    image: mariadb:10.5
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: taskapp
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
